OPTS =-Wall -mpentium -O6 -ffast-math
CC = gcc $(OPTS)

LDFLAGS=-L/usr/local/lib -lfftw -lrfftw -lm

OBJS =	main.o \
	sox-wav.o \
	midi.o \
	analyse.o \
	fft.o

waon: $(OBJS)
	$(CC) -o waon $(OBJS) $(LDFLAGS)

main.o:
	$(CC) -c main.c
sox-wav.o:
	$(CC) -c sox-wav.c
midi.o:
	$(CC) -c midi.c
analyse.o:
	$(CC) -c analyse.c
fft.o:
	$(CC) -c fft.c

clean: 
	rm -f *.o *~ waon *.core
